[package]
name = "turbo"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.11"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
poise = "0.4"
rand = "0.8"
pyo3 = "0.17"

